### ISSUE TITLE
How to using Swift with admob Adaptor

### ISSUE THREAD

**Issue by androidcn** [AppLovin/SDK-Network-Adaptors#12]
How to using Swift with admob Adaptor

**Comment by mszaro** [comment]
Hi @androidcn, I don't believe you need to do anything with our adaptor. You just need to add the Obj-C files to your Xcode project somewhere.

You can certainly interact with Google's SDK using Swift, but you'll have to check their documentation for that. Here's a link: https://developers.google.com/admob/ios/interstitial#helpful_primers - you can click "Swift" above any of the code samples, it seems.
