### ISSUE TITLE
GADMAdapterAppLovinRewardBasedVideoAd link failed

### ISSUE THREAD

**Issue by fresair** [AppLovin/SDK-Network-Adaptors#13]
when using GADMAdapterAppLovinRewardBasedVideoAd.m GADMAdapterAppLovinRewardBasedVideoAd.h

in linking stage, error occur

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADMExtrasAppLovin", referenced from:
      objc-class-ref in GADMAdapterAppLovinRewardBasedVideoAd.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by libern** [comment]
Faced same issue here.

**Comment by mszaro** [comment]
Hi guys, I believe my coworker @gilmincbergapplovin has resolved this issue in a PR ( https://github.com/AppLovin/SDK-Network-Adaptors/pull/14 ), can you give it another go?
