### ISSUE TITLE
AdMob SDK Version 7.7.0 not supported.

### ISSUE THREAD

**Issue by OneSecure** [AppLovin/SDK-Network-Adaptors#15]
AdMob SDK Version 7.7.0 not supported. Please provide a new version adaptor to fit AdMod SDK Version 7.7.0. 
Thanks.

**Comment by mszaro** [comment]
Hi OneSecure, we believe our latest adaptors are compliant with the latest AdMob SDK. Feel free to re-open if you have a counterexample.
