### ISSUE TITLE
Can't Implement Applovin AdMob Mediation

### ISSUE THREAD

**Issue by code4lifevn** [AppLovin/SDK-Network-Adaptors#17]
Dear team,

I can't implement Applovin Mediation with Google Play Service Ad 9.+

Please upgrade your SDK

**Comment by snake-yang** [comment]
have the same problem

**Comment by rihito0907** [comment]
Same problem occurred.

Error message is as such
```
 Fail to instantiate adapter com.applovin.mediation.ApplovinAdapter
 android.os.RemoteException
```

**Comment by thomasmso** [comment]
Hi,

Please let us know if you have any issues integrating with our latest [Android SDK 6.4.0](https://www.applovin.com/integration#androidIntegration).
