### ISSUE TITLE
#import "GADMRewardBasedVideoAdNetworkAdapterProtocol.h" Doesn't Exist?

### ISSUE THREAD

**Issue by szweier** [AppLovin/SDK-Network-Adaptors#19]
Not sure if I'm missing something simple here but I'm trying to implement AppLovin with AdMob and based on the ReadMe here I'm trying to add the `GADMAdapterAppLovinRewardBasedVideoAd.h` file.  But it is trying to import `#import "GADMRewardBasedVideoAdNetworkAdapterProtocol.h"` which doesn't seem like it exists anymore (Using Google-Mobile-Ads-SDK (7.8.1) installed via cocoapods). Is there something I'm missing when trying to implement reward based ads?

Worth noting (I turned on test ads and set my device id as one of the test devices). I ONCE got a video ad served (without adding this file I might add).  I however have not gotten one back since.  It's been well passed the half hour wait time for test ads to be issued and I continue to get 

```
Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}
```

 Any help would be appreciated.

Thanks.

**Comment by rihito0907** [comment]
Same problem

**Comment by rihito0907** [comment]
@mszaro 
Could you fix this issue?

**Comment by mszaro** [comment]
Hey @rihito0907, just saw your tag. Sorry but I don't work on this project any longer, so I am out of the loop. Maybe @applovinjosh or @thomasmso are familiar with any AdMob SDK changes.

**Comment by rihito0907** [comment]
@mszaro Thank you for the information.

**Comment by rihito0907** [comment]
@applovinjosh @thomasmso 
Could you fix this issue?

**Comment by gilmincbergapplovin** [comment]
Hi, 
It seems like there are some headers missing when integrating through cocoapods. To solve that, you would need to download the AdMob SDK from Google:
https://firebase.google.com/docs/admob/ios/download
and add the headers folder "Mediation Adapters" manually.

**Comment by rihito0907** [comment]
@gilmincbergapplovin 
Thank you!
