### ISSUE TITLE
No known instance method for selector 'networkExtras'

### ISSUE THREAD

**Issue by ispiropoulos** [AppLovin/SDK-Network-Adaptors#25]
I have followed the getting started guide, also I have added the Mediation Header folder from the Google Mobile Ads SDK, but I am getting this error on GADMAdapterAppLovinRewardBasedVideoAd.m like 48

**Comment by thomasmso** [comment]
Hi, please check out the new adapters. Please let us know if you are still encountering any errors. Please note that adapter class names have changed, so you might need to update them accordingly in your GADs dashboard.
