### ISSUE TITLE
AdMob adapter context change

### ISSUE THREAD

**Issue by santa010** [AppLovin/SDK-Network-Adaptors#26]
The AdMob android adapter should probably implement OnContextChangedListener as described [here](https://firebase.google.com/docs/admob/android/rewarded-video-adapters). I had a problem with showing reward videos when leaving and re-entering the activity containing the ad and implementing the listener seemed to do the trick.

**Comment by thomasmso** [comment]
Hi, 

Thanks for reaching out. This should be fixed on master now.
