### ISSUE TITLE
Imports need to be updated for iOS SDK 3.5.0

### ISSUE THREAD

**Issue by DiegoAce** [AppLovin/SDK-Network-Adaptors#27]
With the new framework for iOS SDK 3.5.0 the imports need to be changed. 
For example, from 
"ALAdLoadDelegate.h"
to
<AppLovinSDK/ALAdLoadDelegate.h>

**Comment by thomasmso** [comment]
Hi,

Thanks for bringing this issue up. We have updated the imports accordingly.
