### ISSUE TITLE
MoPub Native adapter. CTA button onClick not working.

### ISSUE THREAD

**Issue by simpleforreddit** [AppLovin/SDK-Network-Adaptors#30]
If I uncomment:

` /**
         * use the code below if you would like AppLovin to handle the ad clicks for you:
         *
        @Override
        public void prepare(View view) {
            mView = view;
            mView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    mNativeAd.launchClickTarget(mContext);
                    notifyAdClicked();
                }
            });
            trackImpression(mNativeAd);
        }
        */`

To make clicks register, the view itself has onClick working, however the CTA button inside the view does not and will not respond to clicks.

I can use android:clickable="false" on the button layout to make it work, however this then conflicts with other MoPub native adapters and stops clicks registering for them.

**Comment by simpleforreddit** [comment]
Also to note, if I don't uncomment that code, clicks do not work at all.

**Comment by gilmincbergapplovin** [comment]
Hi, and thanks for reaching out.

If you would like children of the view to become clickable too, you can set the click listener on them within the prepare method. 
For example, assuming that you would like to set the click listener on the CTA button, and its id is native_ad_call_to_action, you should do the following:

public void prepare(View view) {

    Log.i(TAG, "prepare is called.");

    View.OnClickListener clickListener = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            Log.i(TAG, "onClick is called.");

            mNativeAd.launchClickTarget(mContext);

            notifyAdClicked();
        }
    };

    mView = view;
    mView.setOnClickListener(clickListener);
// this is the view that I want to make clickable:
    mView.findViewById(R.id.native_ad_call_to_action).setOnClickListener(clickListener);

    trackImpression(mNativeAd);

}

**Comment by simpleforreddit** [comment]
Perfect, thanks
