### ISSUE TITLE
error building for android with the latest adapter

### ISSUE THREAD

**Issue by ayublin** [AppLovin/SDK-Network-Adaptors#33]
Hello, I am getting this error building my project using the latest version of the adapter:

![image](https://cloud.githubusercontent.com/assets/1355215/23846101/4fb03e64-07fe-11e7-94f5-6ce28e8e722c.png)

I am not getting any error using the previous version of the adapter. Any suggestion? Thanks.

**Comment by gilmincbergapplovin** [comment]
Hi,

Thanks for reporting this. Could you please try using the attached jar instead, and let me know how it went? Just make sure to change the file extension from "txt" to "jar".

[applovin-adapter-new.txt](https://github.com/AppLovin/SDK-Network-Adaptors/files/841445/applovin-adapter-new.txt)

**Comment by ayublin** [comment]
Hey,

Thanks for responding very quickly, I am going to try this now and get back to you asap.

**Comment by ayublin** [comment]
@gilmincbergapplovin whoa, this is perfect, no more error when building the project, and I can also confirm that the ads served properly as well, great job!

**Comment by ayublin** [comment]
@gilmincbergapplovin sorry, one more thing, so I am trying to mediate AppLovin for interstitial ads as well, but I can't see AppLovin in the list of network sources for interstitial ads:

![image](https://cloud.githubusercontent.com/assets/1355215/23911668/12eb8f02-0910-11e7-9427-c612bc0ad2e7.png)

AppLovin only appear for Rewarded Video unity type, is this expected?

**Comment by gilmincbergapplovin** [comment]
Hi,

I am glad to hear that the issue was solved. Thanks for the update.
Regarding interstitials: Our network is not part of the default networks for interstitial integration. You would need to integrate it as a custom event, as described in our docs here:
https://www.applovin.com/integration#adMobIntegration

**Comment by ayublin** [comment]
Ah, got it, I missed that part, thanks again.
