### ISSUE TITLE
Applovin mediation for admob, cannot play reward video

### ISSUE THREAD

**Issue by caosc900224** [AppLovin/SDK-Network-Adaptors#42]
I am implementing reward video, using the mediation code on github and using applovin android sdk 7.2.0, when only using applovin Sdk, everything works well, howerver, after using admob reward ad request, it can show applovin reward ads sometimes, but most of the times, it shows error below:

> 
> android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4371e308 is not valid; is your activity running?
> W/Ads     (24318): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:532)
> W/Ads     (24318): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
> W/Ads     (24318): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
> W/Ads     (24318): 	at android.app.Dialog.show(Dialog.java:286)
> W/Ads     (24318): 	at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
> 951)
> W/Ads     (24318): 	at com.applovin.impl.sdk.bf.run(Unknown Source)
> W/Ads     (24318): 	at android.app.Activity.runOnUiThread(Activity.java:4713)
> W/Ads     (24318): 	at com.applovin.impl.sdk.be.a(Unknown Source)

I load ad by using  mAd = MobileAds.getRewardedVideoAdInstance(mContext), 
and the mContext is the Activity context, and the activity is running, not pause or destroy, could you please check the issue? Thanks

**Comment by thomasmso** [comment]
Hi, 

Thanks for reporting this issue. It has been resolved in AppLovin Android SDK 7.3.0 which is available on our website now.
