### ISSUE TITLE
Applovin Interstitial not showing

### ISSUE THREAD

**Issue by DaniyalRizvi** [AppLovin/SDK-Network-Adaptors#50]
Hi
i am facing an issue where i am not getting applovin ad to be showed
i am using unity and admob mediation and calling applovin through custom event using class name: com.applovin.mediation.AppLovinCustomEventInterstitial
and also using this in AndroidManifest.xml

i am using this adapter
https://github.com/AppLovin/SDK-Network-Adaptors/tree/master/AdMob/Android/Unity
and SDK version 6.3.0
i am getting the following error
Couldnot show interstitial from adapter
java.lang.NullPointerException: Attempt to invoke interface method 'void com.applovin.adview.AppLovinInterstatialAdDialog.setAdDisplayListener(com.applovin.sdk.AppLovinAdDisplayListener)' on a null object reference
at com.applovin.mediation.ApplovinCustomEventinterstatial.showInterstatial(AppLovinCustomEventInterstitial.java:87)

**Comment by gilmincbergapplovin** [comment]
Hi Daniyal,

Thanks for reporting this issue. Since you already gave us a feedback that the new adapter solved the issue, I am closing it.

Best,
Gil
