### ISSUE TITLE
[AdMob] Compiler Error Using SDK Version 3.0.2

### ISSUE THREAD

**Issue by wtowns** [AppLovin/SDK-Network-Adaptors#7]
It looks like ``initBannerAd`` was removed from ALAdView:

```
Libraries/AppLovinCustomEventBanner.m:24:36: No visible @interface for 'ALAdView' declares the selector 'initBannerAd'
```

Looking at the implementation for the Unity wrapper, should it be ``initWithSize`` instead?

**Comment by mszaro** [comment]
Yeah, that's correct. We'll update. Thanks for filing an issue.

**Comment by wtowns** [comment]
:+1:
