### ISSUE TITLE
Integrating Admob and Applovin for mediation.

### ISSUE THREAD

**Issue by mayankjain05** [AppLovin/SDK-Network-Adaptors#72]
Hi

I was trying to integrate applovin with my admob but faced these issues.
1)As I was integrating using this guide -  https://developers.google.com/admob/android/mediation/applovin
I could not see  Placements section and admob needs placement name in order to integrate applovin for banner ads.
2)For rewarded video "placement" field is marked optional in admob console (for applovin) but if I leave it blank it doesnot load ad from applovin.

Regards
Mayank jain

**Comment by mayankjain05** [comment]
I waited for 2 hours,made my admob cpm floor to 20 and then aplovin ads started loading.

**Comment by thomasmso** [comment]
Glad to hear it worked out. I also want to note that we have deprecated placements in lieu of [zones](https://www.applovin.com/integration#iosZonesIntegration).
