### ISSUE TITLE
Is SMART_BANNER supported in AppLovin + AdMob mediation?

### ISSUE THREAD

**Issue by yccheok** [AppLovin/SDK-Network-Adaptors#73]
Hi,

I plan to add AppLovin, as part of my AdMob mediation.

I'm using banner in my app.

From https://github.com/AppLovin/SDK-Network-Adaptors/blob/master/AdMob/Android/AppLovinCustomEventBanner.java#L173 , I realize SMART_BANNER is not supported.

Is there any workaround? - https://stackoverflow.com/questions/48291946/any-good-workaround-to-support-smart-banner-for-admob-mediation-network

Thanks

**Comment by thomasmso** [comment]
Please check out this [branch](https://github.com/AppLovin/SDK-Network-Adaptors/tree/feat/admob_support_for_smart_banners) - the AdMob banner adapters will have support for AdMob's smart banners.
