### ISSUE TITLE
AdMob Mediation Implementation with AppLovin for Unity3D

### ISSUE THREAD

**Issue by kobyle69** [AppLovin/SDK-Network-Adaptors#79]
Hi,

It's currently not clear how to implement AdMob mediation with AppLovin.
Admob instruction, says to download GoogleMobileAdsAppLovinMediation.unitypackage
Ref: https://developers.google.com/admob/unity/mediation/applovin#step_3_import_the_applovin_sdk_and_adapter

While AppLovin docs instruct to download applovin-admob-adapter.jar, and create a custom event through AdMob dashboard.
Ref: https://github.com/AppLovin/SDK-Network-Adaptors/tree/master/AdMob/Android/Unity

Which one is the correct one?

**Comment by thomasmso** [comment]
So there are two ways to integrate AppLovin via AdMob:

1. Via AdMob, and you follow all their instructions. **OR**
2. As custom events contained in this GitHub repo.

**Comment by kobyle69** [comment]
@thomasmso, the guides on AdMob are wrong, there is no longer PlacementId over AppLovin as far as I've noticed. Didn't work for me without setting a PalcementId.

**Comment by thomasmso** [comment]
That is correct, as AppLovin as deprecated placements in lieu of zones. However, if you plan to integrate AppLovin via AdMob, our adapters with zone support is still pending AdMob approval (ETA ~1-2 weeks). The custom events in this GitHub repo has support fro zones already.

More info on integrating AppLovin zones with AdMob -[Android](https://www.applovin.com/integration#adMobIntegration-andriodZones) / [iOS](https://www.applovin.com/integration#iosAdMobIntegration-iosZones).

**Comment by kobyle69** [comment]
@thomasmso That's great to hear.
Actually I just integrated Zones with AdMob.
Interstitial works great, however I get No-Fill for Banner, although my test mode is enabled.

Using Android SDK 7.8.2 and AdMob Adapter

Any word on that?

**Comment by thomasmso** [comment]
There is also a toggle for banners in AppLovin's dashboard, make sure that is "ON". Please see attached image for reference.

![image](https://user-images.githubusercontent.com/5104410/36046121-bc656fd6-0d8c-11e8-882a-1bb8bc0565be.png)

**Comment by kobyle69** [comment]
Yeah saw that, it was enabled during all my tests

**Comment by thomasmso** [comment]
It might also help to reset your device's IDFA in "Settings" -> "Privacy" -> "Advertising" -> "Reset Advertising Identifier"

**Comment by kobyle69** [comment]
Still not luck, same result.
Can you confirm that banner mediation with AdMob is actually working?

**Comment by thomasmso** [comment]
Lets take this conversation off GitHub. My email is thomas.so@applovin.com.
